### ISSUE TITLE
make the navbar look better

### ISSUE THREAD

**Issue by MahakPathak** [vishal02527/My-Strength-Shree-Krishna#328]
![image](https://github.com/user-attachments/assets/b214ba7c-59b8-4f23-8500-70c2c1b3f81a)

**Comment by MahakPathak** [comment]
@vishal02527 can you  please assign me this issue

**Comment by vishal02527** [comment]
@MahakPathak Okay, I can assign this issue to you, only if you will adjust the top navigation bar in the same format in all the pages. and navbar should be responsive across all the devices. Are you ok with that?

**Comment by MahakPathak** [comment]
Yes I will

**Comment by MahakPathak** [comment]
can you please label it will hacktoberfest-accepted also

**Comment by TarunGoel93** [comment]
Hi,

I’d like to make a few improvements:

I will enhance the navbar to make it more visually appealing and ensure it’s fully responsive across different screen sizes.
I noticed that the image below the navbar is stretched and doesn’t fit well within its box. I’ll adjust it so that the image maintains its aspect ratio and fits properly within the fixed box size.
Could you please assign this to me? Thank you!

@vishal02527

**Comment by manastiwari99** [comment]
I would like to work on this issue. Could you please assign me this task

**Comment by annastudent2003** [comment]
@vishal02527 I would like to work on this issue. If you don't mind, can you please assign me this work?
