### ISSUE TITLE
change in background of front page

### ISSUE THREAD

**Issue by Kunal12max** [vishal02527/My-Strength-Shree-Krishna#466]
Respected project admin the background of  front page of the website can be improved by making it more aligned towards spirituality  this will make website looks more good the background will become more appealing making it more attractive please assign this to me @vishal02527 
![Screenshot (189)](https://github.com/user-attachments/assets/c80eb14a-e5ac-4b65-8c4a-ba9edcddb826)

**Comment by KomaLGoyaL02** [comment]
please assign it to me

**Comment by KomaLGoyaL02** [comment]
Thank you sir for assign it to me. But sir, I want to know what kind of background you want for your site.  Sent from Mail for Windows From: Vishal KumarSent: 18 October 2024 23:02To: vishal02527/My-Strength-Shree-KrishnaCc: KomaLGoyaL02; CommentSubject: Re: [vishal02527/My-Strength-Shree-Krishna] change in background of front page (Issue #466) Closed #466 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
