### ISSUE TITLE
Header Section was Overlapped 

### ISSUE THREAD

**Issue by Mallik-vinukonda** [vishal02527/My-Strength-Shree-Krishna#671]
Header section features got overlapped on to each other 
![Screenshot 2024-11-01 at 9 24 37 AM](https://github.com/user-attachments/assets/53a93db9-acd7-4992-a5ab-8a9fd41caff3)

i will fix this issue

**Comment by vishal02527** [comment]
@Mallik-vinukonda adjust navbar across all devices. It will be better if you can put all these buttons in a hamburger icon on mobile screens. Don't forget to attach demo video at the time of raising PR.

**Comment by Mallik-vinukonda** [comment]
> @Mallik-vinukonda adjust navbar across all devices. It will be better if you can put all these buttons in a hamburger icon on mobile screens. Don't forget to attach demo video at the time of raising PR.

Sure ! Thanks for Assigning !

**Comment by Mallik-vinukonda** [comment]
@vishal02527 

here i the modified header ,  I suggest to reduce the links in the Header for better UI , if not i will send you the video and the pull request 

![Screenshot 2024-11-02 at 11 39 28 PM](https://github.com/user-attachments/assets/6d6dae13-6006-4662-ac8c-b9cf44412046)

**Comment by vishal02527** [comment]
@Mallik-vinukonda you can work on this issue to add some links in a drop-down menu.

**Comment by imsudiptaa** [comment]
Hello respected Project Maintainer @vishal02527 ,

I must say that this project  got me  really overwhelmed by seeing that is based on Lord Krishna.
I opened the project and saw some areas to improve, before mentioning or seeing any issue here in GitHub I jumped into fixing those, 
🌟 I fixed the **Header Navbar allignment** , added **Hamburger button** for some links and other links are visible otherwise it will look too empty.
***
![Screenshot 2024-11-03 210328](https://github.com/user-attachments/assets/88e8bf98-9165-4242-97c2-5de7025f7c0e)
***
🌟 I also added **Responsiveness** .


https://github.com/user-attachments/assets/788fba78-351c-4878-aca2-866af94a9329

***
If you kindly assign me with labels of GSSoc & level, I would be glad to sent the Pull request so that it could be merged without any delay.
**Thank You**

**Comment by Mallik-vinukonda** [comment]
@vishal02527   Despite my semester exams, I’ve been setting aside time to work on the project and waited for your approval on the structural changes (dropdown update) . I noticed that, in the meantime, another contributor has submitted a PR for the same issue. I just wanted to check in regarding this. I truly appreciate the opportunity to contribute and will fully respect whatever decision you make on how to proceed. 

![Screenshot 2024-11-03 at 11 01 34 PM](https://github.com/user-attachments/assets/9ca08587-3db0-4daa-a842-91b909f1044b)

**Comment by vishal02527** [comment]
@Mallik-vinukonda I'm not able to see any PR raised by you. Have you raised PR for this issue? Please mention that PR here.

**Comment by vishal02527** [comment]
As this issue has been resolved and PR has been merged successfully so I am closing this issue.
